name: AC Milan PRO Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Save cache
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add cache.json
          git commit -m "update cache" || echo "no changes"
          git push || echo "no push"
